  version: '3'
    
  services:
    web:
      build: .
      command: python van_oak/manage.py migrate; python van_oak/manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/db
        - ./web/static:/code/static
      ports:
        - "443:8000" 