# Generated by Django 3.1.1 on 2020-09-08 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input blank name', max_length=20)),
                ('amount_in_stock', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['type', 'amount_in_stock', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlankTrafaret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input trafaret name', max_length=20)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input compound name', max_length=30)),
                ('amount_in_stock', models.PositiveSmallIntegerField()),
                ('color_rgb', models.CharField(help_text='Input Color RGB code', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input product type name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input product name', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Input price', max_digits=2)),
                ('blanks', models.ManyToManyField(to='shop.Blank')),
                ('compounds', models.ManyToManyField(to='shop.Compound')),
                ('trafaret', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.blanktrafaret')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.producttype')),
            ],
        ),
        migrations.AddField(
            model_name='compound',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.producttype'),
        ),
        migrations.AddField(
            model_name='blanktrafaret',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.producttype'),
        ),
        migrations.AddField(
            model_name='blank',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.producttype'),
        ),
    ]
