# Generated by Django 3.1.1 on 2020-09-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='particular_matches',
            field=models.ManyToManyField(to='shop.BlankTrafaret'),
        ),
    ]
