# Generated by Django 3.1.1 on 2020-09-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200912_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blanktrafaret',
            name='name',
            field=models.CharField(help_text='Input trafaret name', max_length=40),
        ),
        migrations.AlterField(
            model_name='compound',
            name='name',
            field=models.CharField(help_text='Input compound name', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Input product name', max_length=60),
        ),
    ]
