# Generated by Django 3.1.1 on 2020-09-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200912_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
