# Generated by Django 3.1.1 on 2020-09-13 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterizedproduct',
            name='amount_in_stock',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterizedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametrized_products', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='relying_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', related_query_name='properties', to='shop.parameterizedproduct'),
        ),
        migrations.DeleteModel(
            name='ProductStack',
        ),
    ]
